// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LicensesReadLicensesData, LicensesReadLicensesResponse, LicensesCreateLicenseData, LicensesCreateLicenseResponse, LicensesReadLicenseData, LicensesReadLicenseResponse, LicensesUpdateLicenseData, LicensesUpdateLicenseResponse, LicensesDeleteLicenseData, LicensesDeleteLicenseResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, ModuleQrGetStatusResponse, OrganizationsReadOrganizationsData, OrganizationsReadOrganizationsResponse, OrganizationsCreateOrganizationData, OrganizationsCreateOrganizationResponse, OrganizationsReadOrganizationData, OrganizationsReadOrganizationResponse, OrganizationsUpdateOrganizationData, OrganizationsUpdateOrganizationResponse, OrganizationsDeleteOrganizationData, OrganizationsDeleteOrganizationResponse, OrganizationsReadOrganizationUsersData, OrganizationsReadOrganizationUsersResponse, OrganizationsReadOrganizationLicensesData, OrganizationsReadOrganizationLicensesResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class LicensesService {
    /**
     * Read Licenses
     * Retrieve licenses (Superuser only).
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns LicensesPublic Successful Response
     * @throws ApiError
     */
    public static readLicenses(data: LicensesReadLicensesData = {}): CancelablePromise<LicensesReadLicensesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/licenses/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create License
     * Create new license (Superuser only).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns LicensePublic Successful Response
     * @throws ApiError
     */
    public static createLicense(data: LicensesCreateLicenseData): CancelablePromise<LicensesCreateLicenseResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/licenses/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read License
     * Get license by ID (Superuser only).
     * @param data The data for the request.
     * @param data.licenseId
     * @returns LicensePublic Successful Response
     * @throws ApiError
     */
    public static readLicense(data: LicensesReadLicenseData): CancelablePromise<LicensesReadLicenseResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/licenses/{license_id}',
            path: {
                license_id: data.licenseId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update License
     * Update a license (Superuser only).
     * @param data The data for the request.
     * @param data.licenseId
     * @param data.requestBody
     * @returns LicensePublic Successful Response
     * @throws ApiError
     */
    public static updateLicense(data: LicensesUpdateLicenseData): CancelablePromise<LicensesUpdateLicenseResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/licenses/{license_id}',
            path: {
                license_id: data.licenseId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete License
     * Delete a license (Superuser only).
     * @param data The data for the request.
     * @param data.licenseId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteLicense(data: LicensesDeleteLicenseData): CancelablePromise<LicensesDeleteLicenseResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/licenses/{license_id}',
            path: {
                license_id: data.licenseId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ModuleQrService {
    /**
     * Get Status
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getStatus(): CancelablePromise<ModuleQrGetStatusResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/modules/qr/status'
        });
    }
}

export class OrganizationsService {
    /**
     * Read Organizations
     * Retrieve organizations (Available only for superusers).
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns OrganizationsPublic Successful Response
     * @throws ApiError
     */
    public static readOrganizations(data: OrganizationsReadOrganizationsData = {}): CancelablePromise<OrganizationsReadOrganizationsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/organizations/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Organization
     * Create new organization (Superuser only).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns OrganizationPublic Successful Response
     * @throws ApiError
     */
    public static createOrganization(data: OrganizationsCreateOrganizationData): CancelablePromise<OrganizationsCreateOrganizationResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/organizations/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Organization
     * Get organization by ID.
     * @param data The data for the request.
     * @param data.organizationId
     * @returns OrganizationPublic Successful Response
     * @throws ApiError
     */
    public static readOrganization(data: OrganizationsReadOrganizationData): CancelablePromise<OrganizationsReadOrganizationResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/organizations/{organization_id}',
            path: {
                organization_id: data.organizationId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Organization
     * Update an organization.
     * @param data The data for the request.
     * @param data.organizationId
     * @param data.requestBody
     * @returns OrganizationPublic Successful Response
     * @throws ApiError
     */
    public static updateOrganization(data: OrganizationsUpdateOrganizationData): CancelablePromise<OrganizationsUpdateOrganizationResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/organizations/{organization_id}',
            path: {
                organization_id: data.organizationId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Organization
     * Delete an organization (Superuser only).
     * @param data The data for the request.
     * @param data.organizationId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteOrganization(data: OrganizationsDeleteOrganizationData): CancelablePromise<OrganizationsDeleteOrganizationResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/organizations/{organization_id}',
            path: {
                organization_id: data.organizationId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Organization Users
     * Retrieve users for a specific organization from its tenant DB.
     * @param data The data for the request.
     * @param data.organizationId
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readOrganizationUsers(data: OrganizationsReadOrganizationUsersData): CancelablePromise<OrganizationsReadOrganizationUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/organizations/{organization_id}/users',
            path: {
                organization_id: data.organizationId
            },
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Organization Licenses
     * Retrieve licenses for a specific organization.
     * @param data The data for the request.
     * @param data.organizationId
     * @param data.skip
     * @param data.limit
     * @returns LicensesPublic Successful Response
     * @throws ApiError
     */
    public static readOrganizationLicenses(data: OrganizationsReadOrganizationLicensesData): CancelablePromise<OrganizationsReadOrganizationLicensesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/organizations/{organization_id}/licenses',
            path: {
                organization_id: data.organizationId
            },
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}