// This file is auto-generated by @hey-api/openapi-ts

export type AccessPointCreate = {
    name: string;
    location: string;
    device_id: string;
    enabled_modules?: Array<(string)>;
    is_active?: boolean;
    organization_id: string;
};

export type AccessPointPublic = {
    name: string;
    location: string;
    device_id: string;
    enabled_modules?: Array<(string)>;
    is_active?: boolean;
    id: string;
    organization_id: string;
};

export type AccessPointUpdate = {
    name?: (string | null);
    location?: (string | null);
    enabled_modules?: (Array<(string)> | null);
    is_active?: (boolean | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LicenseCreate = {
    tier: LicenseTier;
    addon_modules?: Array<(string)>;
    max_locations: number;
    max_users: number;
    max_devices: number;
    valid_from: string;
    valid_until: string;
    is_active?: boolean;
    license_key?: (string | null);
    created_at?: string;
    organization_id: string;
};

export type LicensePublic = {
    tier: LicenseTier;
    addon_modules?: Array<(string)>;
    max_locations: number;
    max_users: number;
    max_devices: number;
    valid_from: string;
    valid_until: string;
    is_active?: boolean;
    license_key: string;
    created_at?: string;
    id: string;
    organization_id: string;
};

export type LicensesPublic = {
    data: Array<LicensePublic>;
    count: number;
};

export type LicenseTier = 'starter' | 'business' | 'enterprise';

export type LicenseUpdate = {
    tier?: (LicenseTier | null);
    max_locations?: (number | null);
    max_users?: (number | null);
    max_devices?: (number | null);
    valid_until?: (string | null);
    is_active?: (boolean | null);
    addon_modules?: (Array<(string)> | null);
};

export type LogPublic = {
    id: string;
    user_id: (string | null);
    action: string;
    target: string;
    details: (string | null);
    level: string;
    timestamp: string;
    ip_address: (string | null);
    organization_id: (string | null);
};

export type LogsPublic = {
    data: Array<LogPublic>;
    count: number;
};

export type Message = {
    message: string;
};

export type ModulePublic = {
    name: string;
    version: string;
    description: string;
    author: string;
    license_required: boolean;
    is_external: boolean;
};

export type ModulesPublic = {
    data: Array<ModulePublic>;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OrganizationCreate = {
    name: string;
    type?: OrganizationType;
    address: string;
    contact_email: string;
    is_active?: boolean;
    admin_email: string;
    admin_password: string;
};

export type OrganizationPublic = {
    name: string;
    type?: OrganizationType;
    address: string;
    contact_email: string;
    is_active?: boolean;
    id: string;
    db_name?: (string | null);
    created_at: string;
};

export type OrganizationsPublic = {
    data: Array<OrganizationPublic>;
    count: number;
};

export type OrganizationType = 'residential' | 'office' | 'commercial' | 'parking' | 'private';

export type OrganizationUnitCreate = {
    name: string;
    type: string;
    organization_id: string;
};

export type OrganizationUnitPublic = {
    name: string;
    type: string;
    id: string;
    organization_id: string;
    related_unit_id?: (string | null);
};

export type OrganizationUnitUpdate = {
    name?: (string | null);
    type?: (string | null);
    related_unit_id?: (string | null);
};

export type OrganizationUpdate = {
    name?: (string | null);
    type?: (OrganizationType | null);
    address?: (string | null);
    contact_email?: (string | null);
    is_active?: (boolean | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SystemCounts = {
    organizations: number;
    organizations_growth: number;
    users: number;
    users_growth: number;
    licenses: number;
    licenses_growth: number;
};

export type SystemMetrics = {
    cpu_usage: number;
    memory_usage: number;
    db_status: string;
    counts: SystemCounts;
    timestamp: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    organization_id?: (string | null);
    unit_id?: (string | null);
    parent_id?: (string | null);
    is_primary_unit_user?: boolean;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    organization_id?: (string | null);
    unit_id?: (string | null);
    parent_id?: (string | null);
    is_primary_unit_user?: boolean;
    id: string;
    organization_name?: (string | null);
    unit_name?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
    role?: UserRole;
};

export type UserRole = 'admin' | 'staff' | 'resident' | 'visitor';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: (UserRole | null);
    organization_id?: (string | null);
    unit_id?: (string | null);
    parent_id?: (string | null);
    is_primary_unit_user?: (boolean | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AccessPointsReadAccessPointsData = {
    deviceId?: (string | null);
    limit?: number;
    skip?: number;
};

export type AccessPointsReadAccessPointsResponse = (Array<AccessPointPublic>);

export type AccessPointsCreateAccessPointData = {
    requestBody: AccessPointCreate;
};

export type AccessPointsCreateAccessPointResponse = (AccessPointPublic);

export type AccessPointsReadAccessPointData = {
    accessPointId: string;
};

export type AccessPointsReadAccessPointResponse = (AccessPointPublic);

export type AccessPointsUpdateAccessPointData = {
    accessPointId: string;
    requestBody: AccessPointUpdate;
};

export type AccessPointsUpdateAccessPointResponse = (AccessPointPublic);

export type AccessPointsDeleteAccessPointData = {
    accessPointId: string;
};

export type AccessPointsDeleteAccessPointResponse = (Message);

export type LicensesReadLicensesData = {
    limit?: number;
    skip?: number;
};

export type LicensesReadLicensesResponse = (LicensesPublic);

export type LicensesCreateLicenseData = {
    requestBody: LicenseCreate;
};

export type LicensesCreateLicenseResponse = (LicensePublic);

export type LicensesReadLicenseData = {
    licenseId: string;
};

export type LicensesReadLicenseResponse = (LicensePublic);

export type LicensesUpdateLicenseData = {
    licenseId: string;
    requestBody: LicenseUpdate;
};

export type LicensesUpdateLicenseResponse = (LicensePublic);

export type LicensesDeleteLicenseData = {
    licenseId: string;
};

export type LicensesDeleteLicenseResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type ModuleAuditStatsGetSummaryResponse = (unknown);

export type ModuleQrGetStatusResponse = (unknown);

export type ModulesDownloadModuleData = {
    moduleName: string;
};

export type ModulesDownloadModuleResponse = (unknown);

export type ModuleWeatherConnectorGetCurrentWeatherData = {
    city?: string;
};

export type ModuleWeatherConnectorGetCurrentWeatherResponse = (unknown);

export type MonitoringGetMetricsResponse = (SystemMetrics);

export type MonitoringGetLogsData = {
    level?: (string | null);
    limit?: number;
    skip?: number;
    target?: (string | null);
};

export type MonitoringGetLogsResponse = (LogsPublic);

export type MonitoringGetModulesResponse = (ModulesPublic);

export type OrganizationsReadOrganizationsData = {
    limit?: number;
    skip?: number;
};

export type OrganizationsReadOrganizationsResponse = (OrganizationsPublic);

export type OrganizationsCreateOrganizationData = {
    requestBody: OrganizationCreate;
};

export type OrganizationsCreateOrganizationResponse = (OrganizationPublic);

export type OrganizationsReadOrganizationData = {
    organizationId: string;
};

export type OrganizationsReadOrganizationResponse = (OrganizationPublic);

export type OrganizationsUpdateOrganizationData = {
    organizationId: string;
    requestBody: OrganizationUpdate;
};

export type OrganizationsUpdateOrganizationResponse = (OrganizationPublic);

export type OrganizationsDeleteOrganizationData = {
    organizationId: string;
};

export type OrganizationsDeleteOrganizationResponse = (Message);

export type OrganizationsReadOrganizationUsersData = {
    limit?: number;
    organizationId: string;
    skip?: number;
};

export type OrganizationsReadOrganizationUsersResponse = (UsersPublic);

export type OrganizationsReadOrganizationLicensesData = {
    limit?: number;
    organizationId: string;
    skip?: number;
};

export type OrganizationsReadOrganizationLicensesResponse = (LicensesPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UnitsReadUnitsData = {
    limit?: number;
    skip?: number;
};

export type UnitsReadUnitsResponse = (Array<OrganizationUnitPublic>);

export type UnitsCreateUnitData = {
    requestBody: OrganizationUnitCreate;
};

export type UnitsCreateUnitResponse = (OrganizationUnitPublic);

export type UnitsUpdateUnitData = {
    requestBody: OrganizationUnitUpdate;
    unitId: string;
};

export type UnitsUpdateUnitResponse = (OrganizationUnitPublic);

export type UnitsDeleteUnitData = {
    unitId: string;
};

export type UnitsDeleteUnitResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UsersCreateSubUserData = {
    requestBody: UserCreate;
};

export type UsersCreateSubUserResponse = (UserPublic);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);