"""Add advanced user unit relations

Revision ID: 27fed4f8d280
Revises: eb138dced234
Create Date: 2026-01-03 22:37:14.063352

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '27fed4f8d280'
down_revision = 'eb138dced234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizationunit', sa.Column('related_unit_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'organizationunit', 'organizationunit', ['related_unit_id'], ['id'])
    op.add_column('user', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.add_column('user', sa.Column('is_primary_unit_user', sa.Boolean(), nullable=True))
    op.execute("UPDATE \"user\" SET is_primary_unit_user = false")
    op.alter_column('user', 'is_primary_unit_user', nullable=False)
    op.create_foreign_key(None, 'user', 'user', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'is_primary_unit_user')
    op.drop_column('user', 'parent_id')
    op.drop_constraint(None, 'organizationunit', type_='foreignkey')
    op.drop_column('organizationunit', 'related_unit_id')
    # ### end Alembic commands ###
