"""add level to auditlog

Revision ID: c0302491a6fd
Revises: d0a466152143
Create Date: 2026-01-02 23:15:36.984328

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c0302491a6fd'
down_revision = 'd0a466152143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add level as nullable first
    op.add_column('auditlog', sa.Column('level', sa.String(), nullable=True))
    
    # Fill existing rows with 'info'
    op.execute("UPDATE auditlog SET level = 'info' WHERE level IS NULL")
    
    # Set to non-nullable
    op.alter_column('auditlog', 'level', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auditlog', sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('auditlog', 'level')
    # ### end Alembic commands ###
