"""add created_at to user and license

Revision ID: d0a466152143
Revises: 0325c3872311
Create Date: 2026-01-02 23:12:51.976769

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd0a466152143'
down_revision = '0325c3872311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('license', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    
    # Fill existing rows with current timestamp
    op.execute("UPDATE \"license\" SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE \"user\" SET created_at = NOW() WHERE created_at IS NULL")
    
    # Set to non-nullable
    op.alter_column('license', 'created_at', nullable=False)
    op.alter_column('user', 'created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('license', 'created_at')
    # ### end Alembic commands ###
