"""Add OrganizationUnit and OrgType

Revision ID: eb138dced234
Revises: 96b91c61280c
Create Date: 2026-01-03 22:02:40.121604

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'eb138dced234'
down_revision = '96b91c61280c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizationunit',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('organization', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('user', sa.Column('unit_id', sa.Uuid(), nullable=True))
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'resident'::character varying"))
    op.create_foreign_key(None, 'user', 'organizationunit', ['unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'resident'::character varying"))
    op.drop_column('user', 'unit_id')
    op.alter_column('organization', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('organizationunit')
    # ### end Alembic commands ###
