"""Add db_name to Organization

Revision ID: f7c90bfdc0b5
Revises: ecd61bb5bda0
Create Date: 2026-01-03 01:45:32.036903

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f7c90bfdc0b5'
down_revision = 'ecd61bb5bda0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('db_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'db_name')
    # ### end Alembic commands ###
